accounts/urls.py
from django.urls import path
from .views import SignUpView

urlpatterns = [
    path('signup/', SignUpView.as_view(), name='signup'),
]

articles/urls.py
from django.urls import path
from .views import ArticleListView, ArticleDetailView, ArticleEditView, ArticleDeleteView, ArticleCreateView

urlpatterns = [
    path('', ArticleListView.as_view(), name='article_list'),
    path('<int:pk>/', ArticleDetailView.as_view(), name='article_detail'),
    path('<int:pk>/edit/', ArticleEditView.as_view(), name='article_edit'),
    path('<int:pk>/delete/', ArticleDeleteView.as_view(), name='article_delete'),
    path('new/', ArticleCreateView.as_view(), name='article_create'),
]

django_project/urls.py
from django.views.generic.base import TemplateView
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('articles/', include('articles.urls')),
]

pages/urls.py
from django.urls import path
from .views import HomePageView

urlpatterns = [
    path('', HomePageView.as_view(), name='home'),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class CustomUser(AbstractUser):
    age = models.PositiveIntegerField(null=True, blank=True)


# Create your models here.

articles/models.py
from django.conf import settings
from django.db import models
from django.urls import reverse

class Articles(models.Model):
    title = models.CharField(max_length = 255)
    body = models.TextField()
    date = models.DateTimeField(auto_now_add = True)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete =models.CASCADE)

    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse('article_detail', kwargs={'pk':self.pk})
    
class Comments(models.Model):
    article = models.ForeignKey(Articles, on_delete = models.CASCADE)
    comment = models.TextField(max_length = 140)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete = models.CASCADE)

    def __str__(self):
        return self.comment
    
    def get_absolute_url(self):
        return reverse('article_list')

pages/models.py
from django.db import models

# Create your models here.

accounts/forms.py
from unittest.util import _MAX_LENGTH
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import CustomUser
from django import forms

class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = CustomUser
        fields = UserCreationForm.Meta.fields + ('age', 'email',)

class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = CustomUser
        fields = UserChangeForm.Meta.fields

articles/forms.py
from django import forms
from .models import Comments

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comments
        fields =('comment','author')

accounts/views.py
from django.urls import reverse_lazy
from .forms import CustomUserCreationForm
from django.views.generic import CreateView

class SignUpView(CreateView):
    form_class = CustomUserCreationForm
    template_name = 'registration/signup.html'
    success_url = reverse_lazy('login')

articles/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView, UpdateView, DeleteView, CreateView, FormView
from django.urls import reverse_lazy, reverse
from .models import Articles
from django.views import View
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.views.generic.detail import SingleObjectMixin
from .forms import CommentForm

class ArticleListView(LoginRequiredMixin, ListView):
    model = Articles
    template_name = 'article_list.html'

class CommentGet(DetailView):
    model = Articles
    template_name = 'article_detail.html'

    extra_context={'form':CommentForm}

class CommentPost(SingleObjectMixin, FormView):
    model = Articles
    form_class = CommentForm
    template_name = 'article_detail.html'

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        return super().post(request, *args, **kwargs)
    
    def form_valid(self, form):
        comment = form.save(commit=False)
        comment.article = self.object
        comment.save()
        return super().form_valid(form)
    
    def get_success_url(self):
        article= self.get_object()
        return reverse('article_detail', kwargs={'pk':article.pk})
    
class ArticleDetailView(LoginRequiredMixin, View):

    def get(self, request, *args, **kwargs):
        view = CommentGet.as_view()
        return view(request, *args, **kwargs)
    
    def post(self, request, *args, **kwargs):
        view = CommentPost.as_view()
        return view(request, *args, **kwargs)

class ArticleEditView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Articles
    template_name = 'article_edit.html'
    fields = [
        'title',
        'body',
    ]
    def test_func(self):
        obj=self.get_object()
        return obj.author==self.request.user

class ArticleDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Articles
    template_name = 'article_delete.html'
    success_url = reverse_lazy('article_list')
    def test_func(self):
        obj=self.get_object()
        return obj.author==self.request.user

class ArticleCreateView(LoginRequiredMixin, CreateView):
    model = Articles
    template_name = 'article_create.html'
    fields = [
        'title',
        'body',
    ]

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

pages/views.py
from django.shortcuts import render
from django.views.generic import TemplateView

class HomePageView(TemplateView):
    template_name = 'home.html'

templates/article_create.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<h1>New article</h1>
<form action="" method="post">{% csrf_token %}
{{ form|crispy }}
<button class="btn btn-success ml-2" type="submit">Save</button>
</form>
{% endblock content %}

templates/article_delete.html
{% extends "base.html" %}
{% block content %}
<h1>Delete</h1>
<form action="" method="post">{% csrf_token %}
<p>Are you sure you want to delete "{{ article.title }}"?</p>
<button class="btn btn-danger ml-2" type="submit">Confirm</button>
</form>
{% endblock content %}

templates/article_detail.html
{% extends "base.html" %}
{% load crispy_forms_tags %} 
{% block content %}
<div class="article-entry">
<h2>{{ object.title }}</h2>
<p>by {{ object.author }} | {{ object.date }}</p>
<p>{{ object.body }}</p>
</div>
<hr>
<h4>Comments</h4>
{% for comment in object.comments_set.all %}
<p>{{ comment.author }} &middot; {{ comment }}</p>
{% endfor %}
<hr>
<h4>Add a comment</h4>
<form action="" method="post">{% csrf_token %}
{{ form|crispy }}
<button class="btn btn-success ml-2" type="submit">Save</button>
</form>
<p><a href="{% url 'article_edit' articles.pk %}">Edit</a> |
<a href="{% url 'article_delete' articles.pk %}">Delete</a></p>
<p>Back to <a href="{% url 'article_list' %}">All Articles</a>.</p>
{% endblock content %}

templates/article_edit.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<h1>Edit</h1>
<form action="" method="post">{% csrf_token %}
{{ form|crispy }}
<button class="btn btn-info ml-2" type="submit">Update</button>
</form>
{% endblock content %}

templates/article_list.html
{% extends "base.html" %}
{% block title %}Articles{% endblock title %}
{% block content %}
{% for article in articles_list %}
<div class="card">
<div class="card-header">
<span class="font-weight-bold">{{ article.title }}</span> &middot;
<span class="text-muted">by {{ article.author }} |
{{ article.date }}</span>
</div>
<div class="card-body">
{{ article.body }}
</div>
<div class="card-footer text-center text-muted">
    <a href="{% url 'article_edit' article.pk %}">Edit</a> |
    <a href="{% url 'article_delete' article.pk %}">Delete</a>
</div>
<div class="card-footer">
{% for comment in article.comments_set.all %}
<p>
<span class="font-weight-bold">
{{ comment.author }} &middot;
</span>
{{ comment }}
</p>
{% endfor %}
</div>
</div>
<br />
{% endfor %}
{% endblock content %}

templates/base.html
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>{% block title %}Newspaper App{% endblock title %}</title>
<meta name="viewport" content="width=device-width,
initial-scale=1, shrink-to-fit=no">
<!-- Bootstrap CSS -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
    <div class="container">
        <header class="p-3 mb-3 border-bottom">
        <div class="container">
        <div class="d-flex flex-wrap align-items-center justify-content-center
        justify-content-lg-start">
        <a class="navbar-brand" href="{% url 'home' %}">Newspaper</a>
        <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center
        mb-md-0">
        {% if user.is_authenticated %}
        <li><a href="{% url 'article_create' %}" class="nav-link px-2 link-dark">+ New</a></li>
        </ul>
        <div class="dropdown text-end">
        <a href="#" class="d-block link-dark text-decoration-none dropdown-toggle"
        id="dropdownUser1" data-bs-toggle="dropdown" aria-expanded="false">
        {{ user.username }}
        </a>
        <ul class="dropdown-menu text-small" aria-labelledby="dropdownUser1">
        <li><a class="dropdown-item" href="{% url 'password_change'%}">
        Change password</a></li>
        <li><a class="dropdown-item" href="{% url 'logout' %}">Log Out</a></li>
        </ul>
    </div>
    {% else %}
    </ul>
    <div class="text-end">
    <a href="{% url 'login' %}" class="btn btn-outline-primary me-2">
    Log In</a>
    <a href="{% url 'signup' %}" class="btn btn-primary">Sign Up</a>
    </div>
    {% endif %}
    </div>
    </div>
    </header>
    <main>
    {% block content %}
    {% endblock content %}
    </main>
    </div>
<!-- Bootstrap JavaScript Bundle -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

templates/home.html
{%extends "base.html"%}

{%block title%}Home{%endblock title%}

{%block content%}
{%if user.is_authenticated%}
    Hi {{user.username}}
    {{user.age}}
    <p><a href="{%url 'logout'%}">Log Out</a></p>
{%else%}
    <p>You Are Not Logged In</p>
    <a href="{%url 'login'%}">Log In</a>
    <a href="{%url 'signup'%}">Sign Up</a>
{%endif%}
{%endblock content%}